###
###  Android
###

platform :android do

  private_lane :sonarqube_token_available? do
    sonarqube = ENV["SONAR_TOKEN"]
    !(sonarqube.nil? || sonarqube.empty?)
  end

  desc "Pull Request verification"
  lane :pull_request_verification do
    gradle(task: "clean")
    gradle(task: "detekt")
    gradle(task: "lintDebug")
    gradle(task: "jacocoDebugTestReport")
    gradle(task: "jacocoRootReport")
    gradle(task: "sample:assembleDebug")
    if sonarqube_token_available?
      publish_sonarcloud_gradle
    end
  end

  desc "Deploy current code to stage"
  lane :deploy_to_stage do
    gradle(task: "assemble")
    gradle(task: "uploadArchives --no-daemon --no-parallel")
  end

  desc "Deploy current code to production"
  lane :deploy_to_production do
    sh "bash ./release/maven_signing.sh"
    deploy_to_stage
  end
end

desc "Publish new release based on last two tags"
lane :deploy do
  sh "git fetch"

  tagName = ENV["TAG_NAME"].split("/").last

  ENV["VERSION_DEPLOY"] = tagName

  sh "git checkout tags/#{tagName} -b newReleaseFromTag#{tagName}"

  sh "fastlane android deploy_to_production"

  releaseNotes = release_notes(versionDeploy: tagName)
  sh "bash ./delete_release.sh " + tagName
  set_github_release(
    repository_name: ENV["REPO"],
    api_token: ENV["REPO_TOKEN"],
    name: tagName,
    tag_name: tagName,
    description: releaseNotes,
    commitish: ENV["COMMITISH"]
  )
end

lane :run_danger do |options|
  danger_id = options[:danger_id] || lane_context[SharedValues::PLATFORM_NAME].to_s
  danger_file_path = options[:danger_file_path] || lane_context[SharedValues::PLATFORM_NAME].to_s
  danger(
    danger_id: danger_id,
    dangerfile: "danger/#{danger_file_path}/Dangerfile",
    github_api_token: ENV["GITHUB_TOKEN"],
    verbose: true,
  )
end

###
###  Release Notes
###

desc "Generate release notes"
private_lane :release_notes do |params|
  get_previous_tag = lastExpectedVersion(newVersion:params[:versionDeploy])
  tagHashes = sh "git show-ref -s #{get_previous_tag} || git show-ref -s #{params[:versionDeploy]}"

  lane_context[SharedValues::RELEASE_ANALYZED] = true
  lane_context[SharedValues::RELEASE_LAST_TAG_HASH] = tagHashes.split("\n").last
  lane_context[SharedValues::RELEASE_NEXT_VERSION] = params[:versionDeploy]
  lane_context[SharedValues::CONVENTIONAL_CHANGELOG_ACTION_FORMAT_PATTERN] = "(feat|fix|refactor|perf|chore|test|docs|no_type|ci)(:)()(.*)"
  sections = {
    feat: "Features",
    fix: "Bug fixes",
    refactor: "Code refactoring",
    perf: "Performance improvements",
    chore: "Building system",
    test: "Testing",
    docs: "Documentation",
    ci: "CI/CD",
    no_type: "Other work"
  }
  order = ["feat", "fix", "refactor", "perf", "chore", "test", "docs", "ci", "no_type"]
  changelog = conventional_changelog(sections: sections, order: order, display_title: false, display_links: false)
  changelog = changelog ? changelog.gsub("**::**  ", "") : changelog
  "\nRelease notes #{params[:versionDeploy]}
   \nChanges:
   \n#{changelog}"
end

private_lane :danger_token_available? do
  danger = ENV["GITHUB_TOKEN"]
  !(danger.nil? || danger.empty?)
end

after_all do |lane, options|
  if lane == :pull_request_verification
    if danger_token_available?
      run_danger
    end
  end
end

error do |lane, exception, options|
  if lane == :pull_request_verification
    if danger_token_available?
      run_danger
    end
  end
end

# input: 1.2.0; output: 1.1.0
# input: 1.2.2; output: 1.2.1
# input: 3.0.0; output: 2.0.0
lane :lastExpectedVersion do |params|
  releaseNumberArray = params[:newVersion].split(".")
  lastVersion = ""
  calculated = false
  for number in releaseNumberArray.reverse()
    intNumber = number.to_i
    if intNumber != 0 && !calculated
      intNumber -= 1
      calculated = true
    end
    lastVersion = ".#{intNumber}" + lastVersion
  end
  lastVersion[0] = ""

  version = lastVersion
  "#{version}"
end

desc "Publishing Sonarcloud reports via gradle"
private_lane :publish_sonarcloud_gradle do |params|
   # Setup java 11
   ENV["JAVA_HOME"] = ENV["JAVA_HOME_11_X64"]
   gradle(task: "sonarqube")
   # Rollback to java 8
   ENV["JAVA_HOME"] = ENV["JAVA_HOME_8_X64"]
end